services:
  backend:
    build: .
    container_name: club_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    command: npm run dev

  mariadb:
    image: mariadb:11
    container_name: club_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: frontend_users_db
      MYSQL_USER: club_user
      MYSQL_PASSWORD: club_pass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data: